Allow test selection

diff --git a/src/test/runtime/runner b/src/test/runtime/runner
--- a/src/test/runtime/runner
+++ b/src/test/runtime/runner
@@ -1,6 +1,7 @@
 #! /usr/bin/env loki
 
 # ASSUMPTION: running from src/test/runtime
+tests=("$@")
 
 return_code=0
 
@@ -10,21 +11,43 @@ cat <<__HEREDOC
 ==================================================================
 __HEREDOC
 
-for test_file in ../*Tests.sh; do
-    if ! [ -x "$test_file" ]; then
-        continue
-    fi
+loki-log info "Run configuration: <${#tests[@]}: ${tests[*]}>"
 
-    loki-log info "> Test: $(loki-wrap "${SKY}" "$(basename "$test_file")")"
-    echo "⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅"
-    if ! "$test_file"; then
-        loki-log err "Test failed"
-        (( return_code++ ))
-    else
-        loki-log succ "Test passed"
-    fi
+if ! { (( ${#tests[@]} == 1 )) && [ "${tests[0]}" = "./runner" ]; }; then
+    for test_file in "${tests[@]}"; do
+        test_file="../${test_file}Tests.sh"
+        if ! [ -x "$test_file" ]; then
+            continue
+        fi
 
-    echo "=================================================================="
-done
+        loki-log info "> Test: $(loki-wrap "${SKY}" "$(basename "$test_file")")"
+        echo "⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅"
+        if ! "$test_file"; then
+            loki-log err "Test failed"
+            (( return_code++ ))
+        else
+            loki-log succ "Test passed"
+        fi
+
+        echo "=================================================================="
+    done
+else
+    for test_file in ../*Tests.sh; do
+        if ! [ -x "$test_file" ]; then
+            continue
+        fi
+
+        loki-log info "> Test: $(loki-wrap "${SKY}" "$(basename "$test_file")")"
+        echo "⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅"
+        if ! "$test_file"; then
+            loki-log err "Test failed"
+            (( return_code++ ))
+        else
+            loki-log succ "Test passed"
+        fi
+
+        echo "=================================================================="
+    done
+fi
 
 exit $return_code
