add check for successful docker run

diff --git a/src/main/fenrir/core/fenrir-run-docker b/src/main/fenrir/core/fenrir-run-docker
--- a/src/main/fenrir/core/fenrir-run-docker
+++ b/src/main/fenrir/core/fenrir-run-docker
@@ -110,7 +110,13 @@ fi
 image=$(fenrir-read-conf "$task" image)
 image=${image:-"registry.gitlab.com/atpd/progtech/tech-tasks/containers/fenrir-base"}
 
-container=$(docker run -e LOKI_VERBOSE --rm -d "$image")
+container=$(docker run -e LOKI_VERBOSE --rm -d "$image" 2> "${ERR_FILE}")
+status=$?
+
+if (( status != 0 )); then
+    loki-log fail "Cannot start docker"
+    exit $status
+fi
 
 loki-log info "Running on: " "$(docker exec -it "$container" fenrir v)"
 
