Execute tests in subshells

diff --git a/src/main/fenrir/core/fenrir-exec-testcase b/src/main/fenrir/core/fenrir-exec-testcase
--- a/src/main/fenrir/core/fenrir-exec-testcase
+++ b/src/main/fenrir/core/fenrir-exec-testcase
@@ -41,19 +41,55 @@ function save_error_report {
 }
 ###########################################
 
-ecode=0
-
-pretty_print_testname "${testcase}"
-
 echo "    <testcase name=\"${testcase}\">" >> "${REPORT_FILE}"
 if [ -n "$FENRIR_TC_SKIP" ]; then
     echo "      <skipped>Blocking execution</skipped>" >> "${REPORT_FILE}"
 else
-    "$(fenrir-task-path repo)/$testcase" || {
-        ecode=$?
-        save_error_report
-    }
+    pretty_print_testname "${testcase}"
+
+    ( # Running in a subshell => Cannot change file scope
+        ecode=0
+
+        # Set up: *.enter is sourced (current scope)
+        if [ -x "$(fenrir-task-path repo)/$testcase.enter" ]; then
+            source "$(fenrir-task-path repo)/$testcase.enter" || {
+                ecode=$?
+                save_error_report
+            }
+        elif [ -x "$(fenrir-task-path repo)/.enter" ]; then
+             source "$(fenrir-task-path repo)/.enter" || {
+                 ecode=$?
+                 save_error_report
+             }
+        fi
+
+        if (( ecode != 0 )); then
+            loki-log warn "Cannot start the testcase environment: tests are not executed!"
+        else
+            # Run test: fork (child scope)
+            "$(fenrir-task-path repo)/$testcase" || {
+                ecode=$?
+                save_error_report
+            }
+        fi
+
+        # Tear down: *.exit is sourced (current scope)
+        if [ -x "$(fenrir-task-path repo)/$testcase.exit" ]; then
+            source "$(fenrir-task-path repo)/$testcase.exit" || {
+                ecode=$?
+                save_error_report
+            }
+        elif [ -x "$(fenrir-task-path repo)/.exit" ]; then
+             source "$(fenrir-task-path repo)/.exit" || {
+                 ecode=$?
+                 save_error_report
+             }
+        fi
+
+        exit $ecode
+    )
+    ecode=$?
 fi
 echo "    </testcase>" >> "${REPORT_FILE}"
 
-exit $ecode
+exit "$ecode"
diff --git a/src/main/fenrir/core/fenrir-main b/src/main/fenrir/core/fenrir-main
--- a/src/main/fenrir/core/fenrir-main
+++ b/src/main/fenrir/core/fenrir-main
@@ -91,8 +91,6 @@ function switch_solution {
 ###########################################
 echo "$FENRIR_LOGO"
 
-ecode=0
-
 # Initialise score file
 echo -n 0 > "${SCORE_FILE}"
 # Initialise report file
@@ -103,35 +101,42 @@ switch_solution || {
     finalise "$?"
 }
 
-linter_failed=0
+( # Execution scope
+    linter_failed=0
+    ecode=0
 
-for script in $main; do
-    if [ "$script" = "walk-inspections" ]; then
-        fenrir-exec-walk-inspect || {
-            ecode=$?
-            if [ "$blocking" -ne 0 ]; then
-                export FENRIR_TC_SKIP=YES
-            fi
-            linter_failed=1
-        }
-    else
-        fenrir-exec-testcase "$script" || {
-            ecode=$?
-            if [ "$blocking" -ne 0 ]; then
-                export FENRIR_TC_SKIP=YES
-            fi
-        }
+    # Run tests
+    for script in $main; do
+        if [ "$script" = "walk-inspections" ]; then
+            fenrir-exec-walk-inspect || {
+                ecode=$?
+                if [ "$blocking" -ne 0 ]; then
+                    export FENRIR_TC_SKIP=YES
+                fi
+                linter_failed=1
+            }
+        else
+            fenrir-exec-testcase "$script" || {
+                ecode=$?
+                if [ "$blocking" -ne 0 ]; then
+                    export FENRIR_TC_SKIP=YES
+                fi
+            }
+        fi
+    done
+
+    if (( linter_failed == 1 )); then
+        loki-log warn "Some linter inspections have failed: final score is reset to 0"
+        echo -n 0 > "${SCORE_FILE}"
     fi
-done
+
+    exit $ecode
+)
+ecode=$?
 
 loki-log info "$(loki-dup '-' $(( LOKI_COLUMNS - 10 )))"
 
 echo "  </testsuite>" >> "${REPORT_FILE}"
 echo "</testsuites>" >> "${REPORT_FILE}"
-
-if (( linter_failed == 1 )); then
-    loki-log warn "Some linter inspections have failed: final score is reset to 0"
-    echo -n 0 > "${SCORE_FILE}"
-fi
 
 finalise
