Separate run conf from mail.hel
Additionally: branch & task were merged

diff --git a/src/main/loki/funs/loki-points b/src/main/loki/funs/loki-points
--- a/src/main/loki/funs/loki-points
+++ b/src/main/loki/funs/loki-points
@@ -4,7 +4,7 @@
 #   loki-points [+ | -]<number>
 #
 # Add the provided number of points to the global counter.
-# The location of the global counter is defined in '/etc/fenrir/main.hel'.
+# The location of the global counter is defined by '$SCORE_FILE' (see loki-common-const).
 ##
 function loki-points {
 trap '(( JOTUNHEIM_DEPTH -= 2 ))' RETURN
@@ -12,22 +12,18 @@ trap '(( JOTUNHEIM_DEPTH -= 2 ))' RETURN
     local op=${1:0:1}
     local points=${1:1}
 
-    ( # Create a local scope to propagate additional data
-        source "/etc/fenrir/main.hel"
-
-        case "$op" in
-            "+")
-                echo -n $(( points + $(cat "$score") )) > "$score" # 'score' comes from main.hel
-                loki-log succ '(੭>ᴗ<)੭ ' "PASSED"
-                ;;
-            "-")
-                echo -n $(( $(cat "$score") - points )) > "$score"
-                loki-log fault '𐐘💥╾━╤デ╦︻ඞා ' "FAILED"
-                ;;
-            *)
-                loki-log err "loki-points: Unsupported operation <$op>"
-                exit 56
-        esac
-    )
+    case "$op" in
+        "+")
+            echo -n $(( points + $(cat "$SCORE_FILE") )) > "$SCORE_FILE"
+            loki-log succ '(੭>ᴗ<)੭ ' "PASSED"
+            ;;
+        "-")
+            echo -n $(( $(cat "$SCORE_FILE") - points )) > "$SCORE_FILE"
+            loki-log fault '𐐘💥╾━╤デ╦︻ඞා ' "FAILED"
+            ;;
+        *)
+            loki-log err "loki-points: Unsupported operation <$op>"
+            exit 56
+    esac
 }
 # <-----------------------------------------------------------------------loki-points-< #
