Mute adocs

diff --git a/src/main/fenrir/cli/install/install-man b/src/main/fenrir/cli/install/install-man
--- a/src/main/fenrir/cli/install/install-man
+++ b/src/main/fenrir/cli/install/install-man
@@ -9,16 +9,18 @@ loki-prog "Intalling man pages.."
 skip_man=0
 
 type asciidoctor &> /dev/null || {
-    loki-log warn "Cannot find asciidoctor locally"
+    if [ -z "${FENRIR_NO_ADOC}" ]; then
+        loki-log warn "Cannot find asciidoctor locally"
 
-    loki-log warn "Do you want to skip man pages generation? [y|N]"
+        loki-log warn "Do you want to skip man pages generation? [y|N]"
 
-    read -r op
-    if [ "$op" != "y" ] && [ "$op" != "Y" ]; then
-        loki-log err "Terminating.."
-        exit 7
+        read -r op
+        if [ "$op" != "y" ] && [ "$op" != "Y" ]; then
+            loki-log err "Terminating.."
+            exit 7
+        fi
+        skip_man=1
     fi
-    skip_man=1
 }
 
 if (( skip_man == 0 )); then
