v0.3.0

diff --git a/src/main/fenrir/cli/fenrir b/src/main/fenrir/cli/fenrir
--- a/src/main/fenrir/cli/fenrir
+++ b/src/main/fenrir/cli/fenrir
@@ -5,11 +5,40 @@ shift
 
 ######################################################################
 
+url="https://gitlab.com/atpd/progtech/fenrir.git"
+out="/var/fenrir/out"
+err="/var/fenrir/err"
+
+function save_tag_clone {
+    tag=$1
+    if ! git clone --depth 1 --branch "$tag" "$url" /tmp/fenrir > "$out" 2> "$err"; then
+        fenrir-log err "Failed to clone repo"
+        fenrir-log warn "<stdout>" "$(cat "$out")"
+        fenrir-log err "<stderr>" "$(cat "$err")"
+        exit 66
+    fi
+}
+
+function save_clone {
+    if ! git clone --depth 1 "$url" /tmp/fenrir > "$out" 2> "$err"; then
+        fenrir-log err "Failed to clone repo"
+        fenrir-log warn "<stdout>" "$(cat "$out")"
+        fenrir-log err "<stderr>" "$(cat "$err")"
+        exit 66
+    fi
+}
+
+
+######################################################################
+
 infolog="Possible options:
 fenrir help
 fenrir remote <URL>
 fenrir task <TASK ID>
 fenrir run <SOLUTION DIR>
+
+fenrir versions
+fenrir switch [<VERSION> | latest]
 ------------------------------------------------------------------
 fenrir help:
     Info about fenrir util
@@ -23,24 +52,33 @@ fenrir task <TASK ID>:
 
 fenrir run <SOLUTION DIR>:
     Run local tests on the specified local repository
+
+fenrir versions
+    Get all available versions
+
+fenrir switch latest
+    Update up to the latest version
+
+fenrir switch <VERSION>
+    Switch to the specified version (Error is thrown if the version is not available)
+    Run 'fenrir version' to list all available versions
 ------------------------------------------------------------------
 Current settings:
-    * Remote: $(getremote)
+    * Remote: $(fenrir-getremote)
     * Solution branch: $(jq '.branch' '/etc/fenrir/main.json')
     * Blocking: $(jq '.blocking' '/etc/fenrir/main.json')
     * Last installed task: $(jq '.task' '/etc/fenrir/main.json')
 ------------------------------------------------------------------
 Run settings:
-$(jq . "$HOME/.local/bin/custom/pipeline.json")
+$(jq . "$HOME/.fenrir/custom/pipeline.json")
 ------------------------------------------------------------------
-fenrir REPLACEME, 2025
-@_1BAH_
-"
+fenrir $(jq '.version' '/etc/fenrir/main.json'), 2025
+@_1BAH_"
 
 
 function info {
     if [ "$#" -ne 0 ]; then
-        log err -v Too many arguments!
+        fenrir-log err -v Too many arguments!
         exit 15
     fi
 
@@ -50,57 +88,57 @@ function info {
 ######################################################################
 
 function get_index {
-    host=$(getremote)
+    host=$(fenrir-getremote)
     dir=$1
 
-    wget -O /tmp/index "$host/-/raw/main/$dir/index.json" &> /dev/null
+    wget -O /tmp/FENRIR_INDEX "$host/-/raw/main/$dir/index.json" &> /dev/null
     echo -n "*"
 }
 
 function get_custom {
-    host=$(getremote)
+    host=$(fenrir-getremote)
     dir=$1
 
-    for script in $(jq -r .custom[] /tmp/index); do
-        wget -O "$HOME/.local/bin/custom/$script" "$host/-/raw/main/$dir/$script" &> /dev/null
+    for script in $(jq -r .custom[] /tmp/FENRIR_INDEX); do
+        wget -O "$HOME/.fenrir/custom/$script" "$host/-/raw/main/$dir/$script" &> /dev/null
         echo -n "*"
-        chmod +x "$HOME/.local/bin/custom/$script"
+        chmod +x "$HOME/.fenrir/custom/$script"
     done
 }
 
 function get_cfgs {
-    host=$(getremote)
+    host=$(fenrir-getremote)
     dir=$1
 
-    for script in $(jq -r .cfgs[] /tmp/index); do
+    for script in $(jq -r .cfgs[] /tmp/FENRIR_INDEX); do
         wget -O "/etc/fenrir/$script" "$host/-/raw/main/$dir/$script" &> /dev/null
         echo -n "*"
     done
 }
 
 function get_pipeline {
-    host=$(getremote)
+    host=$(fenrir-getremote)
     dir=$1
 
-    wget -O "$HOME/.local/bin/custom/pipeline.json" "$host/-/raw/main/$dir/pipeline.json" &> /dev/null
+    wget -O "$HOME/.fenrir/custom/pipeline.json" "$host/-/raw/main/$dir/pipeline.json" &> /dev/null
     echo -n "*"
 }
 
 function get_meta {
-    branch=$(jq -r .branch /tmp/index)
-    jq ".branch = \"$branch\"" "/etc/fenrir/main.json" > /tmp/INSTALL_FENRIR
-    cat /tmp/INSTALL_FENRIR > "/etc/fenrir/main.json"
+    branch=$(jq -r .branch /tmp/FENRIR_INDEX)
+    jq ".branch = \"$branch\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
+    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
 
-    block=$(jq -r .blocking /tmp/index)
-    jq ".blocking = \"$block\"" "/etc/fenrir/main.json" > /tmp/INSTALL_FENRIR
-    cat /tmp/INSTALL_FENRIR > "/etc/fenrir/main.json"
+    block=$(jq -r .blocking /tmp/FENRIR_INDEX)
+    jq ".blocking = \"$block\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
+    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
 }
 
 ######################################################################
 
 function install_tests {
     if [ "$#" -ne 1 ]; then
-        log err -v Too many arguments!
+        fenrir-log err -v Too many arguments!
         exit 15
     fi
 
@@ -117,36 +155,79 @@ function install_tests {
 
     echo "]"
 
-    jq ".task = \"$task\"" "/etc/fenrir/main.json" > /tmp/INSTALL_FENRIR
-    cat /tmp/INSTALL_FENRIR > "/etc/fenrir/main.json"
+    jq ".task = \"$task\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
+    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
 }
 
 ######################################################################
 
 function set_remote {
     if [ "$#" -ne 1 ]; then
-        log err -v Too many arguments!
+        fenrir-log err -v Too many arguments!
         exit 15
     fi
 
     url=$1
-    jq ".remote = \"$url\"" "/etc/fenrir/main.json" > /tmp/INSTALL_FENRIR
-    cat /tmp/INSTALL_FENRIR > "/etc/fenrir/main.json"
+    jq ".remote = \"$url\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
+    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
 }
 
 ######################################################################
 
 function run {
     if [ "$#" -ne 1 ]; then
-        log err -v Too many arguments!
+        fenrir-log err -v Too many arguments!
         exit 15
     fi
 
-    src=$1
-    jq ".root = \"$src\"" "/etc/fenrir/main.json" > /tmp/INSTALL_FENRIR
-    cat /tmp/INSTALL_FENRIR > "/etc/fenrir/main.json"
+    src=$(realpath "$1")
+
+    if ! [ -d "$src/.git" ]; then
+        fenrir-err -v "The provided file is not a project root"
+        exit 89
+    fi
+
+    jq ".root = \"$src\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
+    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
 
     fenrir-main
+}
+
+######################################################################
+
+function update {
+    if [ "$#" -ne 1 ]; then
+        fenrir-log err -v Too many arguments!
+        exit 15
+    fi
+
+    tag=$1
+
+    if [ "$tag" = "latest" ]; then
+        save_clone
+    elif [ -z "$tag" ]; then
+        fenrir-log err "Empty version"
+        exit 67
+    else
+        save_tag_clone "$tag"
+    fi
+
+    uninstall-fenrir update
+    /tmp/fenrir/src/main/fenrir/cli/install-fenrir update
+
+    fenrir-log succ -v "Successfully switched to '$(jq '.version' '/etc/fenrir/main.json') version"
+}
+
+######################################################################
+
+function get_versions {
+    if [ "$#" -ne 0 ]; then
+        fenrir-log err -v Too many arguments!
+        exit 15
+    fi
+
+    tags=$(curl https://gitlab.com/api/v4/projects/67614102/repository/tags 2> /dev/null)
+    echo "$tags" | jq '.[].name'
 }
 
 ######################################################################
@@ -168,8 +249,16 @@ case "$cmd" in
         run "$@"
     ;;
 
+    "switch")
+        update "$@"
+    ;;
+
+    "versions")
+        get_versions "$@"
+    ;;
+
     *)
-        log err "Command not found"
+        fenrir-log err "Command not found"
         exit 1
     ;;
 esac
diff --git a/src/main/fenrir/core/fenrir-main b/src/main/fenrir/core/fenrir-main
--- a/src/main/fenrir/core/fenrir-main
+++ b/src/main/fenrir/core/fenrir-main
@@ -5,7 +5,7 @@
 repo=$1
 v="-v" # verbosity (replace with "" to mute hints and info logs)
 config_file="/etc/fenrir/main.json"
-pipeline="$HOME/.local/bin/custom/pipeline.json"
+pipeline="$HOME/.fenrir/custom/pipeline.json"
 out="/var/fenrir/out"
 err="/var/fenrir/err"
 pre=$(jq -r '.pre[]' "$pipeline")
@@ -23,15 +23,15 @@ function finish {
 }
 
 function switch_solution {
-    log info "$v" "Switching to branch '$branch'"
+    fenrir-log info "$v" "Switching to branch '$branch'"
 
-    if change-branch "$repo" "$v" "$branch"; then
+    if fenrir-change-branch "$repo" "$v" "$branch"; then
         if cd "$destination/$branch" > "$out" 2> "$err"; then
-            log succ "$v" "Inside solution's directory"
+            fenrir-log succ "$v" "Inside solution's directory"
         else
-            log err "$v" "Failed"
-            log warn "$v" "<stdout>" "$(cat "$out")"
-            log err "$v" "<stderr>" "$(cat "$err")"
+            fenrir-log err "$v" "Failed"
+            fenrir-log warn "$v" "<stdout>" "$(cat "$out")"
+            fenrir-log err "$v" "<stderr>" "$(cat "$err")"
             return 3
         fi
     else
@@ -45,26 +45,26 @@ score_file=$(jq -r '.score' "$config_file")
 echo -n 0 > "$score_file"
 
 for script in $pre; do
-    log info "$v" "--------------------------($script)--------------------------"
-    if ! "$HOME/.local/bin/custom/$script" "$repo" "$v"; then
+    fenrir-log info "$v" "--------------------------($script)--------------------------"
+    if ! "$HOME/.fenrir/custom/$script" "$repo" "$v"; then
         finish
     fi
 done
 
-log info "$v" "--------------------------(switch-solution)--------------------------"
+fenrir-log info "$v" "--------------------------(switch-solution)--------------------------"
 
 if ! switch_solution; then
     finish
 fi
 
 for script in $main; do
-    log info "$v" "--------------------------($script)--------------------------"
-    if ! "$HOME/.local/bin/custom/$script" "$repo" "$v" && [ "$blocking" -ne 0 ]; then
+    fenrir-log info "$v" "--------------------------($script)--------------------------"
+    if ! "$HOME/.fenrir/custom/$script" "$repo" "$v" && [ "$blocking" -ne 0 ]; then
         finish
     fi
 done
 
-log info "$v" "-----------------------------------------------------------"
+fenrir-log info "$v" "-----------------------------------------------------------"
 
 
 
