JSON -> HEL configs custom -> shared update core to use loki (in progress)

diff --git a/src/main/fenrir/cli/install-fenrir b/src/main/fenrir/cli/install-fenrir
--- a/src/main/fenrir/cli/install-fenrir
+++ b/src/main/fenrir/cli/install-fenrir
@@ -1,295 +1,74 @@
 #! /usr/bin/env bash
 
-#shopt -s globstar
+out=(">" "/dev/null")
+in_docker=""
+verbose=""
 
-CLI_DIR=$(dirname "$(realpath "$0")")
-CORE_UTILS_DIR=$(realpath "${CLI_DIR}/../core")
-CFGS_DIR=$(realpath "${CLI_DIR}/../configs")
-BASIC_UTILS_DIR=$(realpath "${CLI_DIR}/../custom")
+while (( $# > 0 )); do
+    case "$1" in
+    -v)
+        out=()
+        verbose="-v"
+        ;;
+    -d)
+        in_docker="1"
+        ;;
+    esac
 
-while IFS='=' read -r key value; do
-    if [ "$key" = "version" ]; then
-        VERSION=$value
-    fi
-done < "$CLI_DIR/fenrir.properties"
-
-update=""
-docker_update=""
-v="-v"
-
-###################################################################
-
-pushd "$CORE_UTILS_DIR" &> /dev/null
-
-cd loki
-
-./install.loki
-
-sudo mv /tmp/FENRIR_HEADER /usr/local/bin/loki
-sudo chmod +x /usr/local/bin/loki
-
-source /usr/local/bin/loki
-
-popd &> /dev/null
+    shift
+done
 
 #################################################################
-
-if [ "$1" = "update" ]; then
-    loki-log info "$v" "Updating fenrir up to version @$VERSION"
-    update=true
-fi
-
-if [ "$1" = "docker" ]; then
-    echo "[ INFO  ] Updating fenrir up to the latest version: \"$VERSION\""
-    update=true
-    docker_update=true
-    v=""
-fi
-
+#                         VERIFY SUDO                           #
 #################################################################
 
-if [ "$(id -u)" -ne 0 ]; then
-    if [ -n "$update" ]; then
-        loki-log err "$v" "THIS SHOULD NOT HAVE HAPPENED! CONTACT US!"
-    fi
-
-    loki-log err "$v" "The script must be run under sudo!"
+if ! [ "$(id -u)" -eq 0 ]; then
+    echo -e "\033[1m\033[38;5;196m[ ERROR ]\033[0m \033[38;5;197mᕙ( •̀ ᗜ •́ )ᕗ  \033[0mThe script must be run in a \033[1mprivileged mode\033[0m (sudo)!"
     exit 111
 fi
 
-###################################################################
-
-[ -n "$SUDO_USER" ] && user=$SUDO_USER || user=$USER
-loki-log info "$v" "Installing fenrir @$VERSION for '$user' user"
+echo "PROGRESS >> Assembling the build script.."
 
 #################################################################
-
-loki-log info "$v" "> Identifying OS.."
-
-case "$(uname -s)" in
-    Linux*)
-        os_pref_home="/home"
-        loki-log info "$v" ">> OS is LINUX"
-    ;;
-    Darwin*)
-        os_pref_home="/Users"
-        loki-log info "$v" ">> OS is MACOS"
-    ;;
-#    CYGWIN*)
-#        os=Cygwin
-#    ;;
-#    MINGW*)
-#        os=MinGw
-#    ;;
-#    MSYS_NT*)
-#        os=MSys
-#    ;;
-    *)
-        loki-log warn "$v" ">> Unsupported OS: '$(uname -s)'"
-        loki-log warn "$v" ">> Do you agree to continue? (Potentially dangerous) [yes|no]"
-        read -r op
-
-        if [ "$op" != "yes" ]; then
-            loki-log err "$v" "Terminating.."
-            exit 3
-        fi
-    ;;
-esac
-
+#                       ASSEMBLE INSTALLER                      #
 #################################################################
 
-loki-log info "$v" "> Validating environment.."
+CLI_DIR=$(dirname "$(realpath "$0")") # 'cli' directory
+BUILD_SCRIPT="/tmp/FENRIR_BUILD_SCRIPT"
 
-if [ -d "/etc/fenrir" ]; then
-    loki-log warn "$v" ">> Directory '/etc/fenrir' already exists"
-    loki-log warn "$v" ">> Remove existing '/etc/fenrir' [yes|no]"
-    read -r op
-
-    if [ "$op" = "yes" ]; then
-        loki-log info "$v" ">>> Removing '/etc/fenrir'.."
-        rm -fr /etc/fenrir
-    else
-        loki-log err "$v" "Terminating.."
-        exit 3
-    fi
+if [ -f "$BUILD_SCRIPT" ]; then
+    eval "echo \"[ INFO  ] Found an old build script: <$BUILD_SCRIPT>\" ${out[*]}"
+    rm -fr "$BUILD_SCRIPT" &> /dev/null
 fi
 
-if [ -d "/var/fenrir" ]; then
-    loki-log warn "$v" ">> Directory '/var/fenrir' already exists. Run uninstaller to remove it"
-    loki-log warn "$v" ">> Remove existing '/var/fenrir'? [yes|no]"
-    read -r op
 
-    if [ "$op" = "yes" ]; then
-        loki-log info "$v" ">>> Removing '/var/fenrir'.."
-        rm -fr /var/fenrir
-    else
-        loki-log err "$v" "Terminating.."
-        exit 3
-    fi
-fi
-
-if ! type jq &> /dev/null; then
-    loki-log err "$v" ">> 'jq' is not installed"
-    exit 4
-fi
-
-if ! type wget &> /dev/null; then
-    loki-log err "$v" ">> 'wget' is not installed"
-    exit 4
-fi
-
-for cmd in "$CORE_UTILS_DIR"/*; do
-    if ! [ -f "$cmd" ]; then
-        continue
-    fi
-
-    name=$(basename "$cmd")
-
-    if type "$name" &> /dev/null; then
-        location=($(type "$name")) # FIXME: SC2207
-        if [ -n "$docker_update" ]; then
+( # Do not pollute the global variable scope
+    first=1
+    for script in install/*; do
+        if [[ $script == "install-fenrir" ]]; then
             continue
         fi
 
-        loki-log warn "$v" ">> Command <$name> already exists: '${location[2]}'"
-        loki-log warn "$v" ">> After installation it will be overridden. Continue? [yes|no]"
-        read -r op
+        eval "echo \"[ INFO  ] Inlining module <$script>..\" ${out[*]}"
 
-        if [ "$op" != "yes" ]; then
-            loki-log err "$v" "Terminating.."
-            exit 3
+        file=$(basename "$script")
+        pattern="#include <$file>"
+
+        if (( first == 1 )); then
+            sed -e "/$pattern/r $script" -e "/$pattern/d" install/install-fenrir > $BUILD_SCRIPT
+            first=0
+        else
+            sed -i -e "/$pattern/r $script" -e "/$pattern/d" $BUILD_SCRIPT
         fi
-    fi
-done
+    done
+)
 
-loki-log succ "$v" "> Ready to be installed!"
+chmod +x $BUILD_SCRIPT
 
-#################################################################
+eval "echo \"[ INFO  ] The final build script is <$BUILD_SCRIPT>\" ${out[*]}"
+echo "PROGRESS << DONE"
 
-loki-log info "$v" "> Creating '/etc/fenrir'.."
+CLI_DIR="$CLI_DIR" FENRIR_INSTALL_VERBOSE="$verbose" LOKI_VERBOSE="$verbose" IN_DOCKER="$in_docker" $BUILD_SCRIPT
+# TODO save to local repo
 
-mkdir -p /etc/fenrir
-chown "$user" /etc/fenrir
-
-loki-log succ "$v" "> Done"
-
-#################################################################
-
-loki-log info "$v" "> Creating '/var/fenrir'.."
-
-mkdir -p /var/fenrir
-chown "$user" /var/fenrir
-
-loki-log succ "$v" "> Done"
-
-#################################################################
-
-loki-log info "$v" "> Installing core.."
-
-for cmd in "$CORE_UTILS_DIR"/*; do
-    name=$(basename "$cmd")
-
-    if [ -d "$cmd" ]; then
-        continue
-    fi
-
-    if ! cp "$cmd" "/usr/local/bin/$name"; then
-        loki-log err "$v" "Terminating.."
-        exit 10
-    fi
-done
-
-loki-log succ "$v" "> Done"
-
-#################################################################
-
-loki-log info "$v" "> Setting all configs.."
-
-for cfg in "$CFGS_DIR"/*; do
-    name=$(basename "$cfg")
-
-    if ! {
-        cp "$cfg" "/etc/fenrir/$name" &&
-        chown "$user" "/etc/fenrir/$name"
-    }; then
-        loki-log err "$v" "Terminating.."
-        exit 10
-    fi
-done
-
-sudo chmod -t /tmp
-jq ".version = \"$VERSION\"" "/etc/fenrir/main.json" > /tmp/INSTALL_FENRIR
-cat /tmp/INSTALL_FENRIR > "/etc/fenrir/main.json"
-sudo chmod +t /tmp
-
-loki-log succ "$v" "> Done"
-
-#################################################################
-
-loki-log info "$v" "> Installing basic utils.."
-
-if ! mkdir -p "$os_pref_home/$user/.fenrir/custom/walk"; then
-    loki-log err "$v" "> Unable to create local storage"
-    exit 189
-fi
-
-chown "$user" "$os_pref_home/$user/.fenrir"
-chown "$user" "$os_pref_home/$user/.fenrir/custom"
-chown "$user" "$os_pref_home/$user/.fenrir/custom/walk"
-
-for util in "$BASIC_UTILS_DIR"/* "$BASIC_UTILS_DIR"/**/*; do
-    relative_path=${util#$BASIC_UTILS_DIR/}
-
-    if [ -d "$util" ]; then
-        continue
-    fi
-
-    if ! {
-        cp "$util" "$os_pref_home/$user/.fenrir/custom/$relative_path" &&
-        chown "$user" "$os_pref_home/$user/.fenrir/custom/$relative_path"
-    }; then
-        loki-log err "$v" "Terminating.."
-        exit 10
-    fi
-done
-
-loki-log succ "$v" "> Done"
-
-###################################################################
-
-loki-log info "$v" "> Installing cli tool.."
-
-cat "$CLI_DIR/fenrir" > "/usr/local/bin/fenrir"
-chmod +x "/usr/local/bin/fenrir"
-
-loki-log succ "$v" "> Done"
-
-###################################################################
-
-loki-log info "$v" "> Installing autocompletion.."
-
-cp "`which fenrir-autocomplete`" "/etc/bash_completion.d/"
-
-loki-log warn "$v" "> Run 'source ~/.bashrc' or reload terminal to apply autocompletion"
-
-loki-log succ "$v" "> Done"
-
-###################################################################
-
-loki-log info "$v" "> Installing uninstaller.."
-
-if ! {
-    cp "$CLI_DIR/uninstall-fenrir" "/usr/local/bin/uninstall-fenrir" &&
-    chmod +x "/usr/local/bin/uninstall-fenrir"
-}; then
-    loki-log err "$v" "Terminating.."
-    exit 19
-fi
-
-loki-log succ "$v" "> Done"
-
-###################################################################
-
-update="" # Unmute
-
-[ -z "$docker_update" ] && loki-log succ "$v" "Installation has finished!"
+# TODO BUILD SCRIPT CHOWN!
diff --git a/src/main/fenrir/core/fenrir-change-branch b/src/main/fenrir/core/fenrir-change-branch
--- a/src/main/fenrir/core/fenrir-change-branch
+++ b/src/main/fenrir/core/fenrir-change-branch
@@ -1,24 +1,31 @@
 #! /usr/bin/env loki
 
-verbosity=$1
-branch=$2
-destination=$(fenrir-getroot)
-out="/var/fenrir/out"
-err="/var/fenrir/err"
+##
+# Usage:
+#   fenrir-change-branch <branch name>
+#
+# Checks out to the provided branch
+##
+
+EXP_ARGC=1
+#include <verify-argc>
+
+branch=$1
+destination=$(fenrir-read-conf main root)
 
 ##############
 
-pushd "$destination" &> /dev/null
+pushd "$destination" &> /dev/null || {
+    loki-log err "Cannot switch to '$destination'"
+    exit 7
+}
 
-loki-log info "$verbosity" "Switching branch to '$branch'"
+loki-log info "Switching branch to '$branch'"
 
-if git switch "$branch" > "$out" 2> "$err"
-then
-    loki-log succ "$verbosity" "Switched to '$branch'"
+if lokiw git switch "$branch"; then
+    loki-log succ "Switched to '$branch'"
 else
-    loki-log err "$verbosity" "Failed"
-    loki-log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    loki-log err "$verbosity" "<stderr>" "$(cat "$err")"
+    loki-log fail "Cannot check out to '$branch'"
     popd &> /dev/null
     exit 1
 fi
diff --git a/src/main/fenrir/core/fenrir-main b/src/main/fenrir/core/fenrir-main
--- a/src/main/fenrir/core/fenrir-main
+++ b/src/main/fenrir/core/fenrir-main
@@ -1,12 +1,20 @@
 #! /usr/bin/env loki
 
-#UNCOMMENT# cat ~/key > ~/.ssh/id_rsa
+##
+# Usage:
+#   fenrir-main [nl] [nz]
+#
+# Executes task validation pipeline.
+#
+# Options:
+#    nl     See fenrir-run '-nl' option
+#    nz     See fenrir-run '-nz' option
+##
 
-# TODO Simplify??
-# Since we execute via 'Loki', we have to shift args
-if [[ $1 == "${BASH_SOURCE[0]}" ]]; then
-    shift
-fi
+#include <shift-args>
+
+# TODO ???
+#UNCOMMENT# cat ~/key > ~/.ssh/id_rsa
 
 if [ "$1" = "nl" ]; then
     NL=1
@@ -18,45 +26,36 @@ if [ "$1" = "nz" ]; then
     shift
 fi
 
-v=${1} # verbosity (replace with "" to mute hints and info logs)
-config_file="/etc/fenrir/main.json"
-pipeline="$HOME/.fenrir/custom/pipeline.json"
-out="/var/fenrir/out"
-err="/var/fenrir/err"
-pre=$(jq -r '.pre[]' "$pipeline")
-main=$(jq -r '.main[]' "$pipeline")
-branch=$(jq -r '.branch' "$config_file")
-destination=$(jq -r '.root' "$config_file")
-blocking=$(jq -r '.blocking' "$config_file")
+pre=$(fenrir-read-conf -a pipeline pre)
+main=$(fenrir-read-conf -a pipeline main)
+branch=$(fenrir-read-conf main branch)
+destination=$(fenrir-read-conf main root)
+blocking=$(fenrir-read-conf main blocking)
 
 ###########################################
 
-function finish {
+function finalise {
     # Print score
     echo "Final score: $(cat "$score_file")"
     exit 0
 }
 
 function switch_solution {
-    if [ "$branch" = "--" ]; then
-        if cd "$destination" > "$out" 2> "$err"; then
-            loki-log succ "$v" "Inside solution's directory"
+    if [ "$branch" = "--" ]; then # Special alias for multi-branch tasks
+        if lokiw cd "$destination"; then
+            loki-log succ "Inside solution's directory"
             return
         else
-            loki-log err "$v" "Failed"
-            loki-log warn "$v" "<stdout>" "$(cat "$out")"
-            loki-log err "$v" "<stderr>" "$(cat "$err")"
+            loki-log fail "Failed to change directory"
             return 3
         fi
     fi
 
-    if fenrir-change-branch "$v" "$branch"; then
-        if cd "$destination/$branch" > "$out" 2> "$err"; then
-            loki-log succ "$v" "Inside solution's directory"
+    if fenrir-change-branch "$branch"; then
+        if lokiw cd "$destination/$branch"; then
+            loki-log succ "Inside solution's directory"
         else
-            loki-log err "$v" "Failed"
-            loki-log warn "$v" "<stdout>" "$(cat "$out")"
-            loki-log err "$v" "<stderr>" "$(cat "$err")"
+            loki-log fail "Cannot change directory"
             return 3
         fi
     else
@@ -66,39 +65,51 @@ function switch_solution {
 
 
 # initialise score file
-score_file=$(jq -r '.score' "$config_file")
+score_file=$(fenrir-read-conf main score)
 echo -n 0 > "$score_file"
 
 for script in $pre; do
-    loki-log info "$v" "--------------------------($script)--------------------------"
-    if [ -n "$NZ" ] && [ "$script" = "task-zero" ]; then
-        loki-log warn "$v" "Running with '--no-zero' option"
-        continue
-    fi
+    loki-log info "--------------------------($script)--------------------------"
+    if [ "$script" = "task-zero" ]; then
+        if [ -n "$NZ" ]; then
+            loki-log warn "Running with '--no-zero' option"
+            continue
+        fi
 
-    if ! "$HOME/.fenrir/custom/$script" "$v"; then
-        finish
+        if ! "${FENRIR_HOME}/shared/task-zero"; then
+            finalise
+        fi
+    else
+        if ! "$(fenrir-task-path repo)/$script"; then
+            finalise
+        fi
     fi
 done
 
-loki-log info "$v" "--------------------------(switch-solution)--------------------------"
+loki-log info "--------------------------(switch-solution)--------------------------"
 
 if ! switch_solution; then
-    finish
+    finalise
 fi
 
 for script in $main; do
-    loki-log info "$v" "--------------------------($script)--------------------------"
-    if [ -n "$NL" ] && [ "$script" = "walk-inspections" ]; then
-        loki-log warn "$v" "Running with '--no-lint' option"
-        continue
-    fi
+    loki-log info "--------------------------($script)--------------------------"
+    if [ "$script" = "walk-inspections" ]; then
+        if [ -n "$NL" ]; then
+            loki-log warn "Running with '--no-lint' option"
+            continue
+        fi
 
-    if ! "$HOME/.fenrir/custom/$script" "$v" && [ "$blocking" -ne 0 ]; then
-        finish
+        if ! "${FENRIR_HOME}/shared/walk-inspections"; then
+            finalise
+        fi
+    else
+        if ! "$(fenrir-task-path repo)/$script" && [ "$blocking" -ne 0 ]; then
+            finalise
+        fi
     fi
 done
 
-loki-log info "$v" "-----------------------------------------------------------"
+loki-log info "-----------------------------------------------------------"
 
-finish
+finalise
diff --git a/src/main/fenrir/core/fenrir-run b/src/main/fenrir/core/fenrir-run
--- a/src/main/fenrir/core/fenrir-run
+++ b/src/main/fenrir/core/fenrir-run
@@ -1,38 +1,42 @@
 #! /usr/bin/env loki
 
-out="/var/fenrir/out"
-err="/var/fenrir/err"
-
+##
+# Usage:
+#   fenrir-run [-i] [-nl|--no-lint] [-nz|--no-zero] <SOLUTION DIRECTORY>
+#
+# Test the provided solution. The test must be set beforehand with 'fenrir-task' command.
+# This command is an interface. For the detailed execution pipeline see 'fenrir-main'.
+#
+# Options:
+#    -i                 Run test inside the provided directory without cloning it
+#                       WARNING! In case of test's impurity it might produce some side-effects
+#   -nz, --no-zero      Skip task0 validation
+#   -nl, --no-lint      Skip linting stage (walk-inspections)
+##
 
 function local_clone {
     from=$1
     to=$(fenrir-tmp -d)
 
-    loki-log info "$SILENT" "Cloning repo to '$to'.."
+    loki-log info "Cloning repo to '$to'.."
 
-    if ! git clone "$from" "$to" > "$out" 2> "$err"; then
-        loki-log err  "$SILENT" "Failed to clone locally"
-        loki-log warn "$SILENT" "<stdout>" "$(cat "$out")"
-        loki-log err  "$SILENT" "<stderr>" "$(cat "$err")"
+    if ! lokiw git clone "$from" "$to"; then
+        loki-log fail '(シ. .)シ' "Failed to clone locally"
         exit 56
     fi
 
-    jq ".root = \"$to\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
-    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
+    fenrir-set-conf main "root" "$to"
 }
 
 ######################################################################
 ##                         VERIFY ARGUMENTS                         ##
 ######################################################################
 
-# Since we execute via 'Loki', we have to shift args
-if [[ $1 == "${BASH_SOURCE[0]}" ]]; then
-    shift
-fi
+#include <shift-args>
 
-SILENT="-v"
 NO_LINT=""
 NO_ZERO=""
+INLINE=""
 
 hit=0
 path=""
@@ -47,14 +51,14 @@ while [ "$#" -ne 0 ]; do
             NO_ZERO=YES
         ;;
 
-        "-s")
-            SILENT=""
+        "-i")
+            INLINE=YES
         ;;
 
         *)
             if [ $hit -ge 1 ]; then
-                loki-log err "$SILENT" '(＃°Д°)' Wrong arguments count!
-                loki-log err "$SILENT" "Expected <1> but got <$(( $# + hit ))>"
+                loki-log err '(＃°Д°)' Wrong arguments count!
+                loki-log err "Expected <1> but got <$(( $# + hit ))>"
                 exit 15
             fi
 
@@ -68,8 +72,8 @@ while [ "$#" -ne 0 ]; do
 done
 
 if [ "$hit" -ne 1 ]; then
-    loki-log err "$SILENT" '(＃°Д°)' Wrong arguments count!
-    loki-log err "$SILENT" "Expected <1> but got <$hit>"
+    loki-log err '(＃°Д°)' Wrong arguments count!
+    loki-log err "Expected <1> but got <$hit>"
     exit 15
 fi
 
@@ -79,23 +83,32 @@ fi
 
 src=$(realpath "$path")
 
-if ! [ -d "$src/.git" ]; then
-    loki-log err "$SILENT" '(╬▔皿▔)╯' "The provided file is not a project root"
+if [ "$(fenrir-read-conf main branch)" = "-" ]; then
+    loki-log err 'ᕙ( •̀ ᗜ •́ )ᕗ' "The task was not set!"
     exit 89
 fi
 
-local_clone "$src"
+if ! [ -d "$src/.git" ]; then
+    loki-log err '(╬▔皿▔)╯' "The provided file is not a project root"
+    exit 89
+fi
+
+if [ -n "$INLINE" ]; then
+    fenrir-set-conf main "root" "$src"
+else
+    local_clone "$src"
+fi
 
 if [ -n "$NO_LINT" ]; then
     if [ -n "$NO_ZERO" ]; then
-        fenrir-main nl nz "$SILENT"
+        fenrir-main nl nz
     else
-        fenrir-main nl "$SILENT"
+        fenrir-main nl
     fi
 else
     if [ -n "$NO_ZERO" ]; then
-        fenrir-main nz "$SILENT"
+        fenrir-main nz
     else
-        fenrir-main "$SILENT"
+        fenrir-main
     fi
 fi
